### ISSUE TITLE
Возможность отправки заказа без авторизации

### ISSUE THREAD

**Issue by evgeniyloznevoy** [artikus11/art-woocommerce-order-fast#5]
Здравствуйте! Плагин замечательный, но есть проблема.
В woocoommerce включена функция возможности заказа без авторизации, и если оформлять заказ обычным способом - он создается без проблем.
Но функция быстрого заказа не работает без авторизации, консоль выдает ошибку 401. В коде плагина я не нашел явную проверку на авторизацию.
Нужно, чтобы быстрый заказ срабатывал для неавторизованных юзеров. А лучше, чтобы он создавал юзера на основе номера телефона, что он ввел.

**Comment by artikus11** [comment]
Доброго! Хм, странное поведение, не проверял в такой настройке, проверю поправлю если потребуется

**Comment by evgeniyloznevoy** [comment]
> Доброго! Хм, странное поведение, не проверял в такой настройке, проверю поправлю если потребуется

Здравствуйте! Спасибо за оперативную обратную связь! Если у вас появится решение, напишите пожалуйста. 
Ваш плагин единственный из актуальных что я нашел, который предоставляет функцию быстрого заказа именно из корзины, как нормальный заказ. Большинство других плагинов делают просто "купить в 1 клик" как заявку с формы обратной связи. Так что он очень полезен.

Дам немного более подробную информацию:

В WC у нас включены функции:
+ Допускать оформление заказов без создания учётной записи
+ Разрешить пользователям вход в существующий аккаунт при оформлении заказа
+ Позволять клиенту создавать учётную запись во время оформления заказа
+ Позволять клиенту создавать учётную запись на странице "Мой аккаунт"
+ При создании учётной записи автоматически генерируется имя пользователя, основанное на имени, фамилии или адресе электронной почты
+ Отправка пользователю ссылки для установки пароля при создании новой учётной записи

При классическом оформлении заказа через /checkout все работает прекрасно, даже если клиент не авторизован.
Также, с помощью вашего плагина, функция быстрого заказа для авторизованного пользователя тоже работает исправно, заказ создается в админке с пометкой "Быстрый заказ".

А вот если клиент не авторизован, ничего не происходит и консоль выводит ошибку 401. 
Только вот почему так происходит и на каком этапе он обязательно проверяет авторизацию, пока не ясно. Я посмотрел весь код и не нашел проверку на авторизацию. А WC должен давать возможность делать заказ без авторизации.
Есть идея, что можно было бы сделать 2 поля - телефон и электронную почту, и регать нового юзера, если он не авторизован.

В плагине я переписывал только стили, весь функционал ваш штатный.
Суть быстрого заказа как раз в том, чтобы клиент не тратил время на регистрацию, так что этот момент очень важен.

**Comment by artikus11** [comment]
@evgeniyloznevoy попробовал с вашими настройками в режиме инкогнито, все работает. Форма отправляется заказа создается. 

Дайте отчет о сайт, если это возможно
![image](https://user-images.githubusercontent.com/16116688/236433747-89104699-b9b6-4b6d-8a77-8c1462b3df32.png)

Попробую у себя воспроизвести сайт с вашими настройками и плагинами

**Comment by evgeniyloznevoy** [comment]
@artikus11 вот, оставил необходимую информацию, этого достаточно? Спасибо что даете обратную связь.

`
### WordPress Environment ###

WordPress address (URL): https://dev.***
Site address (URL): https://dev.***
WC Version: 7.4.0
REST API Version: ✔ 7.4.0
WC Blocks Version: ✔ 9.4.3
Action Scheduler Version: ✔ 3.5.4
Log Directory Writable: ✔
WP Version: 6.2
WP Multisite: –
WP Memory Limit: 600 МБ
WP Debug Mode: ✔
WP Cron: ✔
Language: ru_RU
External object cache: ✔

### Server Environment ###

Server Info: nginx/1.22.1
PHP Version: 7.4.3-4ubuntu2.18
PHP Post Max Size: 100 МБ
PHP Time Limit: 600
PHP Max Input Vars: 20000
cURL Version: 7.68.0
OpenSSL/1.1.1f

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.11.2-MariaDB-1:10.11.2+maria~ubu2204-log
Max Upload Size: 100 МБ
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ На вашем сервере не включён класс SoapClient - некоторые плагины шлюзов
использующие SOAP могут не работать как ожидалось.

DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.4.0
WC Database Prefix: wp_

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (40) ###

Template Library and Redux Framework: от Extendify – 4.3.19
A-Z Categories List: от Ivan Matveev  – 0.1.1
Accordion Blocks: от Phil Buchanan – 1.5.0
Advanced Custom Fields PRO: от Delicious Brains – 5.12.2
Advanced Woo Search: от ILLID – 2.65
Ajax Cart AutoUpdate for WooCommerce: от taisho – 1.5.5
AJAX Login and Registration modal popup - PRO: от Maxim K – 2.05
FiboSearch - AJAX Search for WooCommerce (Pro): от FiboSearch Team – 1.14.1
Akismet Anti-Spam: от Automattic – 5.0.1
Art WooCommerce Order Fast: от Artem Abramovich – 1.2.0
Contact Form 7: от Takayuki Miyoshi – 5.6.4
Cyr-To-Lat: от Сергей Бирюков
Михаил Кобзарёв
Игорь Гергель – 5.4.0

Google XML Sitemaps: от Auctollo – 4.1.7
Loco Translate: от Тим Уитлок (Tim Whitlock) – 2.6.3
MailPoet: от MailPoet – 3.102.1
Max Mega Menu: от megamenu.com – 2.9.8
Mini Ajax Cart for WooCommerce: от HashThemes – 1.1.2
Qty Increment Buttons for WooCommerce: от taisho – 2.7.5
reCaptcha for WooCommerce: от I Thirteen Web Solution – 2.37
Redis объектный кэш: от Till Krüss – 2.2.4
Responsive Lightbox & Gallery: от dFactory – 2.4.1
Поддержка SVG: от Benbodhi – 2.5.5
Visual Term Description Editor: от Shea Bunge – 1.8.1
Shipping Method Description for WooCommerce: от Thomas Charbit – 1.2.6
Woocommerce Variations Table - Grid: от Spyros Vlachopoulos – 1.3.11
Метод доставки СДЭК для Woocommerce: от WooDev – 2.2.0.6
WooCommerce Group Attributes: от weLaunch – 1.7.1
WooCommerce Product Image Flipper: от jameskoster – 0.4.2
WooCommerce RBSPayment Checkout Gateway - ZVS Fork: от RBSPayment – 3.5.3
WooCommerce: от Automattic – 7.4.0 (доступно обновление до версии 7.6.1)
Почта России EMS для юр.лиц: от WooDev – 1.1.5
Yoast SEO: от Команда Yoast – 19.7.2
WP All Export Pro: от Soflyy – 1.7.8
Яндекс.Метрика: от Yandex – 1.1.6
YITH WooCommerce Customize My Account Page: от YITH – 3.7.0
YITH WooCommerce Questions and Answers Premium: от YITH – 1.3.7
YITH WooCommerce Wishlist Premium: от YITH – 3.4.0
Yml for Yandex Market Pro: от Maxim Glazunov – 4.5.1
Yml для Yandex Market: от Максим Глазунов – 3.10.5
Предзаказы на сайте (кастомный плагин) – 0.1.0

### Dropin Plugins (2) ###

advanced-cache.php: advanced-cache.php
object-cache.php: Redis Object Cache Drop-In

### Must Use Plugins (2) ###

er.php: от  –
Gonzales MU: от Tomasz Dobrzyński – 1.0.5

### Settings ###

API Enabled: –
Force SSL: –
Currency: RUB (руб)
Currency Position: right_space
Thousand Separator: 
Decimal Separator: 
Number of Decimals: 0
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
Order datastore: WC_Order_Data_Store_CPT

### WC Pages ###

Ссылка магазина: ❌ Страница не задана
Корзина: #23709 - /cart/
Оформление заказа: #23710 - /checkout/
Мой аккаунт: #23711 - /my-account/
Правила и условия: ❌ Страница не задана

### Theme ###

Тема кастомная

### Status report information ###

Generated at: 2023-05-05 14:34:49 +03:00
`

**Comment by artikus11** [comment]
@evgeniyloznevoy Да, вполне достаточно. Вот только, есть у меня подозрение что проблема не в моем плагине, а в каком-то и ваших. Вон вижу у вас и плагин изменения личного кабинета  и кеширование включено. Я бы посоветовал поотключать плагины все и проверить.

**Comment by evgeniyloznevoy** [comment]
@artikus11 Вы были правы, конфликт с плагином "Redis объектный кэш"

**Comment by artikus11** [comment]
Рад, что все прояснилось. Хотя с редисом еще проверю, может можно обойти его как то

**Comment by evgeniyloznevoy** [comment]
@artikus11 Да, в этом и проблема, избавиться от этого плагина нет возможности, он необходим. А как их подружить - пока не получается. Я написал хук, который должен отключать редис на странице корзины, но это не дало результата:

`
add_action( 'init', 'check_cart_page' );
function check_cart_page() {
    if( function_exists( 'is_cart' ) && is_cart() ) {
        // Если это страница корзины, отключаем Redis Object Cache
        global $wp_object_cache;
        $wp_object_cache->redis_status = false;
    }
}

`

**Comment by artikus11** [comment]
Ну тут скорее не отключать надо, а сбрасывать кеш. Хотя надо проверить, так сложно что-то конкретное подсказать

**Comment by evgeniyloznevoy** [comment]
@artikus11  Тут выяснилось, что проблема видимо не в этом (или не только в этом)
На локальном сервере без редиса все работает.
На dev. сервере, с отключенным редисом все равно форма без авторизации не работает. Я его полностью отключил.

**Comment by artikus11** [comment]
@evgeniyloznevoy на тестовом теперь отключайте последовательно все плагины кроме нужных и проверяйте. На локалке с редисом проверил, проблем не наблюдается особых, работает

**Comment by evgeniyloznevoy** [comment]
@artikus11 В общем, проблема решена. Оказалось, что так как на dev сервере стоял внешний пароль для входа на сайт, это также блокировало запрос к серверу и заказ не создавался. Убрали защиту и все заработало.

Причем на стандартные заказы через /checkout/ это не распространялось.

Спасибо вам за помощь и обратную связь.

**Comment by artikus11** [comment]
@evgeniyloznevoy Фигасе как у вас все сложно) Но если заработало, то хорошо. Рад, что все получилось
